version: '3.6'
services:
  frontend:
    build: ./frontend
  main:
    build: ./main
    ports:
      - '8080:8080'
    depends_on:
      - serviceName: mongodb
      - serviceName: rabbitmq
  admin:
    build: ./admin
    ports:
      - '8081:8081'
    depends_on:
      - serviceName: mysql
      - serviceName: rabbitmq

  # DATABASES
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'nest_admin'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'admin'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
  mongodb:
    image: 'bitnami/mongodb:5.0'
    ports:
      - '27017:27017'
    expose:
      - '3306'
  rabbitmq:
    image: 'rabbitmq:3.10-management'
    ports:
      - '5672:5672'
      - '15672:15672'
    expose:
      - '5672'
      - '15672'
