version: '3.6'
services:
  frontend:
    build: ./frontend
  admin:
    build: ./admin
    ports:
      - '8081:8081'
    depends_on:
      - serviceName: mysql

  # DATABASES
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'nest_admin'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'admin'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'mRi5PUDVsnynzkZHcyF8nDDrqUB9BoRdK3rh0r372usZad6x'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'pLNNkG2ihRNUtTtuzgTFdpdLDNsob33UOFaKDIEk2eOJjNft'
    ports:
      - '3306:3306'
    expose:
      - '3306'
