apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
        - name: main
          image: 683312808679.dkr.ecr.eu-central-1.amazonaws.com/fullerstack-service-main:latest
