apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_DATABASE
              value: nest_admin
            - name: MYSQL_USER
              value: admin
            - name: MYSQL_PASSWORD
              value: mRi5PUDVsnynzkZHcyF8nDDrqUB9BoRdK3rh0r372usZad6x
            - name: MYSQL_ROOT_PASSWORD
              value: pLNNkG2ihRNUtTtuzgTFdpdLDNsob33UOFaKDIEk2eOJjNft
          ports:
            - containerPort: 3306
